### ISSUE TITLE
use IIIF auth API

### ISSUE THREAD

**Issue by eroux** [buda-base/buda-iiif-server#10]
Once the auth is done, it should be indicated in the images which users can't access. It seems it's mostly a matter of adding the auth service to the `info.json`, see [this example](https://iiif.io/api/auth/1.0/#example-description-resource-with-authentication-services)

**Comment by eroux** [comment]
I'm taking another look at this, it's quite interesting and it shouldn't be too difficult to implement, maybe we could do that while we're in the iiif business?

**Comment by MarcAgate** [comment]
Done in commit 11ddedb which provides a way to use auth (or not) and login or external profiles (however using the same services endpoints)
