### ISSUE TITLE
error 500 fetching first image of volume

### ISSUE THREAD

**Issue by berger-n** [buda-base/buda-iiif-server#12]
in some Volumes of http://library.bdrc.io/show/bdr:I1PD96684 
eg http://library.bdrc.io/show/bdr:V1PD96684_I1PD106654, http://library.bdrc.io/show/bdr:V1PD96684_I1PD106655,
http://library.bdrc.io/show/bdr:V1PD96684_I1PD106657 
but not http://library.bdrc.io/show/bdr:V1PD96684_I1PD106656,
manifest is fetched successfully but there is a 500 error fetching first image: http://iiif.bdrc.io/image/v2/bdr:V1PD96684_I1PD106657::I1PD1066530003.jpg/full/full/0/default.jpg

**Comment by MarcAgate** [comment]
This is resource dependant as the first image is returned for other volumes: http://iiif.bdrc.io/image/v2/bdr:V1PD96684_I1PD106685::I1PD1066850003.jpg/full/full/0/default.jpg
It is now returning a 404 coming from s3 client which cannot find the _Works/ff/W1PD96684/images/W1PD96684-I1PD106657/I1PD1066530003.jpg_ resource.

**Comment by MarcAgate** [comment]
we have the same issue with http://iiif.bdrc.io/image/v2/bdr:V1PD96685_I1PD105064::I1PD1051040006.tif/info.json where s3 returns:
`S3 client failed for identifier Works/4f/W1PD96685/images/W1PD96685-I1PD105064/I1PD1051040006.tif >> 404`

**Comment by eroux** [comment]
@MarcAgate can you look this so that we can finish the iiif server side of things? Note that some aspects of this bug are actually [this other unrelated bug](https://github.com/buda-base/buda-iiif-presentation/issues/28) so don't bother with them

**Comment by MarcAgate** [comment]
We got rid of the /image/v2 part of the url so http://iiif.bdrc.io/image/v2/bdr:V1PD96685_I1PD105064::I1PD1051040006.tif/info.json has become http://iiif.bdrc.io/bdr:V1PD96685_I1PD105064::I1PD1051040006.tif/info.json, which fails.

According to https://github.com/buda-base/buda-iiif-presentation/issues/28  http://localhost:8080/bdr:V1PD96685_I1PD105064::I1PD1050640006.tif/info.json is the valid url (replacing I1PD1051040006.tif by I1PD1050640008.tif which is the valid image name)

Therefore I think we can close this issue which has its cause in the manifest referring to a wrong image name.

**Comment by eroux** [comment]
ok thanks
