### ISSUE TITLE
cookie mechanism for images

### ISSUE THREAD

**Issue by eroux** [buda-base/buda-iiif-server#13]
if we want support inclusion of protected images through simple `<img>` tags we need to support passing the token in an alternate way, as in this case it cannot be passed in the header (see [this question](https://stackoverflow.com/questions/46642960/authorization-header-in-img-src-link) and [this one](https://stackoverflow.com/questions/13725054/protecting-image-resources-with-oauth2-bearer-tokens?rq=1)). So we could probably use cookies for this case. We don't have to support that now, but we might in the future so it's important that we're cautious about the assumptions we make, including in the bdrc-auth-lib library (that should support this kind of case)

**Comment by eroux** [comment]
Elaborating on that idea (see [here](https://github.com/BuddhistDigitalResourceCenter/public-digital-library/issues/34)), what needs to be done is to create a `/setcookie` path that would take no argument and would inspect the headers for the token. In case the token is valid, it would answer by setting the token in the [Set-Cookie](https://developer.mozilla.org/fr/docs/Web/HTTP/Headers/Set-Cookie) http header. A few ideas for the cookie header:
- the `Expires` value could be that of the token
- no need to set `Domain`
- `HttpOnly` could be set (that would be more secure)
- `cookie-name` could be something like `bdrc-auth-token`

**Comment by MarcAgate** [comment]
We could also do this directly in our authFilter based on any query parameter (so the /setcookie endpoint wouldn't be necessary)

**Comment by eroux** [comment]
well, I really prefer having to set that in the apps, we don't want that kind of mechanism to be used everywhere `bdrc-auth-lib` is used... So the lib should allow that to be achieved by an app, but it should be in the app's hands to decide if and how this feature will be used

**Comment by MarcAgate** [comment]
That's the way it is as the filter implementation is not part of bdrc-auth-lib and can be different for any app (ldspdi, iiifserv or iiifpres). Is that what you meant ?

**Comment by eroux** [comment]
We need a mechanism to [invalidate the cookie](https://stackoverflow.com/questions/5285940/correct-way-to-delete-cookies-server-side), either by:
- renaming the current endpoint to `cookie/set` and add a `cookie/unset`
- changing the code so that when the cookie endpoint is called with no token, it invalidates the cookie

I think the first solution is best, but the second is ok for me too.

**Comment by MarcAgate** [comment]
that's implemented here : https://github.com/buda-base/buda-iiif-server/blob/master/src/main/java/de/digitalcollections/iiif/hymir/image/frontend/IIIFImageApiController.java#L108

Moreover, the auth filter first seeks a token in the header "authorization" and in case it finds none, it checks for a cookie named "bdrc-auth-token" in order to retreive a valid token.
The cookie is set by calling /setcookie with a valid token in the "authorization" header.
At logout /setcookie is called with no token in the header so the cookie can be discarded (setting its max age to zero)
