### ISSUE TITLE
implement country restriction

### ISSUE THREAD

**Issue by eroux** [buda-base/buda-iiif-server#16]
We have basically two options:
- use Auth0 (see [here](https://auth0.com/rules/add-country))
- implement it on the iiif server itself (not reading from the auth token), which is most costly but more secure (through [this method](https://www.baeldung.com/geolocation-by-ip-with-maxmind) for instance)

**Comment by MarcAgate** [comment]
The second option is definitely more secure: it's basically one more test in the existing auth filter. However, it is more secure only if we assume that the mapping IP-Country is fully reliable: is it really the case ?. If not, then a mix of the two options might be preferable. What do you think ?

**Comment by xristy** [comment]
IP addr - country relations are pretty reliable. The addr blocks are assigned by ICANN to countries and only a few smaller countries re-sell part of their blocks making those cases unreliable. The other issue is VPNs which are used to spoof location information,  but these are likely hard to access in the PRC which is our main concern as far as region restrictions,  and we only need to use best efforts.

**Comment by eroux** [comment]
@MarcAgate this can be closed right?

**Comment by MarcAgate** [comment]
Yes! It's been implemented here: [https://github.com/buda-base/buda-iiif-server/blob/master/src/main/java/de/digitalcollections/iiif/myhymir/ResourceAccessValidation.java#L50](https://github.com/buda-base/buda-iiif-server/blob/master/src/main/java/de/digitalcollections/iiif/myhymir/ResourceAccessValidation.java#L50)

**Comment by eroux** [comment]
ok thanks
