### ISSUE TITLE
error on fetching resized image

### ISSUE THREAD

**Issue by berger-n** [buda-base/buda-iiif-server#26]
http://iiif.bdrc.io/bdr:V22084_I0886::08860003.tif/full/,600/0/default.png returns error 400
http://iiif.bdrc.io/bdr:V22084_I0886::08860003.tif/full/full/0/default.png is ok
(see http://library.bdrc.io/show/bdr:W22084)

**Comment by berger-n** [comment]
depends on vertical resolution
http://iiif.bdrc.io/bdr:V22084_I0886::08860002.tif/full/,600/0/default.jpg works
because its height is greater than 600

**Comment by berger-n** [comment]
https://github.com/buda-base/public-digital-library/commit/d7ca784ecbecabb06b8eb86648e4f3ea16c57c8f fixes the issue.

**Comment by berger-n** [comment]
reopening this because something is not working anymore
mirador can't load images on scroll view :
![image](https://user-images.githubusercontent.com/33383857/54142093-3da2bf00-4427-11e9-9905-cc9b1f7fc788.png)
see http://library.bdrc.io/show/bdr:W22084 (using original mirador jsdelivr package)

**Comment by eroux** [comment]
can you paste the url of one image that doesn't work?

**Comment by berger-n** [comment]
http://iiif.bdrc.io/bdr:V22084_I0886::08860023.tif/full/4632,/0/default.jpg

**Comment by berger-n** [comment]
the problem come from here: https://github.com/buda-base/mirador/blob/a6fc975fc13652b72f0ac159f381e8db771058e2/js/src/viewer/manifestListItem.js#L110 
can be easy to fix

**Comment by eroux** [comment]
I think we should understand where the issue comes from, is it from the new version of openseadragon, the version of mirador or the iiif server?

**Comment by berger-n** [comment]
not from mirador nor from openseadragon because I reverted http://library.bdrc.io/show/bdr:W22084 to usual jsdelivr package with builtin openseadragon:
![image](https://user-images.githubusercontent.com/33383857/54145401-3fbc4c00-442e-11e9-9ebb-c927a9b337b0.png)

to me it seems that server "policy" on handling unavailable image dimensions has changed

**Comment by eroux** [comment]
the problems is that the width of the thumbnails is dependent on the width of the screen, and there doesn't seem to be any limit to the growth... this is a problem because iiif servers don't have to support scaling above the native resolution (see the `MAY` in [this paragraph](https://iiif.io/api/image/2.1/#size)). I suspect this is due to a combination of a bug in Mirador and the css changes you made that trigger it. In any case, Mirador 2 is not maintained so we'll have to fix it...

**Comment by eroux** [comment]
actually, we could just request the `/full/full` version and Mirador would scale it up / down if it needs to... I think that would be even more simple and would be more efficient from a systemic point of view

**Comment by berger-n** [comment]
scaling above the native resolution seem a waste of resource indeed
I've already fixed it in Mirador locally

**Comment by berger-n** [comment]
fixed
see https://github.com/buda-base/mirador/commit/cb3067158c2c71cf56b07ac48fba0a229261f4ca
