### ISSUE TITLE
png images with tiff content

### ISSUE THREAD

**Issue by berger-n** [buda-base/buda-iiif-server#27]
opening http://library.bdrc.io/show/bdr:W12827 png images won't load
see http://iiif.bdrc.io/bdr:V12827_I2061::020610003.tiff/full/max/0/default.png , http://iiif.bdrc.io/bdr:V12827_I2065::020650001.tiff/full/max/0/default.png ,  http://iiif.bdrc.io/bdr:V12827_I2068::020680001.tiff/full/max/0/default.png etc.
actually these seem to be tiff images renamed as png

**Comment by eroux** [comment]
weird, you're right, these png seem to actually be tiffs... I would expect the bug to be in [this function](https://github.com/buda-base/buda-iiif-server/blob/master/src/main/java/de/digitalcollections/iiif/myhymir/image/business/BDRCImageServiceImpl.java#L370) but I cannot see anything suspicious...

**Comment by MarcAgate** [comment]
I confirm it's actually redirected and not processed as png. More to come...

**Comment by MarcAgate** [comment]
Fixed as of commit 0a96b49
