### ISSUE TITLE
serving static images

### ISSUE THREAD

**Issue by eroux** [buda-base/buda-iiif-server#31]
In order to serve the error images, we should be able to serve an image in

```
src/main/resources/static/abc.def
```

when requesting the id

```
http://iiif.bdrc.io/static::abc.def/
```

**Comment by MarcAgate** [comment]
Do you want it to be served as is (i.e without any processing at the provided size and format) ?

**Comment by eroux** [comment]
no, it should be a regular iiif image that we can request with the image api

**Comment by eroux** [comment]
static images should come from the bucket `static-images.bdrc.io`, the usual credentials should be able to read images. The path should be mapped directly:

```
http://iiif.bdrc.io/static::abc.def/
```

should look for the image with the key

```
s3://static-images.bdrc.io/abc.def
```

**Comment by MarcAgate** [comment]
Done as of commit 4c4bab6 . See:

http://iiif.bdrc.io/static::error-copyright.png/info.json

http://iiif.bdrc.io/static::error-copyright.png/full/full/0/default.webp
