### ISSUE TITLE
white image bug when treating some images

### ISSUE THREAD

**Issue by eroux** [buda-base/buda-iiif-server#32]
Some grayscale images are buggy when a modified image is treated. For instance

http://iiif.bdrc.io/bdr:V1PD127393_I1PD127464::I1PD1274640004.jpg/full/max/0/default.jpg

is fine while

http://iiif.bdrc.io/bdr:V1PD127393_I1PD127464::I1PD1274640004.jpg/full/max/90/default.jpg

is almost entirely white. Note that in the first case the original .jpg is accessed so it doesn't go through the image saving pipeline with turbojpeg. So there may be another bug with the way turbojpeg is handled. We should verify that and if the bug is indeed in the turbojpeg plugin, report a bug [here](https://github.com/dbmdz/imageio-jnr)

**Comment by eroux** [comment]
see https://github.com/dbmdz/imageio-jnr/issues/34

In the meantime, it would be best to change the imagewriter in the case of grayscale images, @MarcAgate does it look feasible?

**Comment by MarcAgate** [comment]
Yes, it will be done today. We have three image qualities: grayscale, black and white (bitonal) and color, so we'll temporarily associate (when the requested format is jpeg and the quality is GRAY) the com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageWriter.

**Comment by eroux** [comment]
thanks!

**Comment by MarcAgate** [comment]
fixed as of commit a630763

**Comment by eroux** [comment]
nice, thanks!
