### ISSUE TITLE
copyright + restricted in China fails

### ISSUE THREAD

**Issue by eroux** [buda-base/buda-iiif-server#36]
in this case:

http://iiif.bdrc.io/bdr:V1KG1418_I1KG1521::I1KG15210004.tif/full/,600/0/default.png

we have

```
   adm:access    bdr:AccessRestrictedInChina ;
   adm:license   bdr:LicenseCopyrighted ;
```

which should make the first 20 / last 20 images work (including the one linked above). But we have a 401 instead.

**Comment by MarcAgate** [comment]
fixed as of commit 3a74405

http://iiif.bdrc.io/bdr:V1KG1418_I1KG1521::I1KG15210014.tif/full/,600/0/default.png 

http://iiif.bdrc.io/bdr:V1KG1418_I1KG1521::I1KG15210034.tif/full/,600/0/default.png
