### ISSUE TITLE
not having the tbrc intro pages in the pdf export

### ISSUE THREAD

**Issue by eroux** [buda-base/buda-iiif-server#39]
it's very easy to get the number of TbrcIntroPages in the data (it's in volumeInfo). This gives number X (often 0 or 2), and we should skip the first X pages in the PDF export.

**Comment by MarcAgate** [comment]
Done as of commit dac8f98. However, do we still have a way to efficiently display these introduction pages? I believe their content has some value anyway.

**Comment by xristy** [comment]
I don't think there's any info in coversheet image that isn't present in the metadata, but I could be wrong

**Comment by MarcAgate** [comment]
It looks like bdg:W22084 doesn't contain all data we have on its two intro pages. At first quick view, unless I am mistaken, Material info is missing (book), but also description (13x55 cm) and scanning info (siti enterprises, etc...)

**Comment by eroux** [comment]
the two pages are still accessible through iiif, they're just not in the manifests... but I think that for these old scans, maybe we could go through them and encode the missing bits... that's another project though, for another issue! Thanks a lot
