### ISSUE TITLE
add metadata in the PDF export

### ISSUE THREAD

**Issue by eroux** [buda-base/buda-iiif-server#40]
Some metadata should be added to the exported PDF, such as:
- the prefLabel of the work in Unicode
- a reference to BDRC with the URI
- a license indication (should be available in the admin data of the item)
- a URI indication

the reference to iText should be removed

**Comment by MarcAgate** [comment]
This has been implemented as of commit db71562. We could add more custom metadata to it in order to get a little closer to the info we currently have in BDRC intro pages. WDYT ?

**Comment by eroux** [comment]
Why not, I think author is a common field... What else do you propose?

**Comment by MarcAgate** [comment]
If set, I suggest we add :

Author, Number of volumes, Current volume, Biblio note, Catalog info, Publisher, Publisher place, LCCN

All these are available from the work resource model we already have when creating ArchiveInfo.

**Comment by eroux** [comment]
maybe the LCCN is a bit superfluous, but if the others are easy to add then yes, let's do it!

**Comment by MarcAgate** [comment]
All added (but LCCN) as of commit 1ebb6de

**Comment by eroux** [comment]
thanks! I think it's ok now, let's close it. I can't see the custom metadata in my (admittedly basic) PDF viewer, but what's there is enough I think
