### ISSUE TITLE
pdf images cropped

### ISSUE THREAD

**Issue by berger-n** [buda-base/buda-iiif-server#41]
see pdf from http://library.bdrc.io/show/bdr:V22084_I0978

![image](https://user-images.githubusercontent.com/33383857/61453369-34d67280-a95e-11e9-8e12-823c55f803bd.png)

seems to be the same in any volume of http://library.bdrc.io/show/bdr:W22084 or http://library.bdrc.io/show/bdr:W12827

**Comment by MarcAgate** [comment]
That's a tough one... Why would the itextpdf Image class would behave differently with images coming from these works? Each page being sized after the Image size, I have to check if java BufferedImage and itextpdf Image returns the same dimension for the same S3 image, for these works. More to come...

**Comment by eroux** [comment]
maybe it's a tiff thing

**Comment by MarcAgate** [comment]
Image size are identical in itextpdf and BufferedImage... It looks like Tiff images can be treated with specific methods in itexpdf...

**Comment by eroux** [comment]
I think the best way to handle that is to write a few lines of codes with just itext as a dependency that demonstrates the problem (on just one image) and send that as a bugreport to itext

**Comment by MarcAgate** [comment]
The problem has been fixed as of commit 6d419c8. I actually moved away from Itext pdf lib and implemented a [Apache PDFBox](https://pdfbox.apache.org/) solution. Two main reasons to that: 1) it solves the problem immediately and 2) The licensing: Apache PdfBox is Apache Licence 2.0  while I realized that Itextpdf was actually AGPLv3 (if I understood everything I read [here and there](https://itextpdf.com/en/resources/faq/legal/itext-5-legacy/can-i-bundle-itext-my-non-commercial-software)). 
Right now, I still have to improve a few things to that implementation (mainly, quit using a temp file before caching the pdf doc bytes array) and to test it thoroughly.

**Comment by eroux** [comment]
Well, in any case we need to report the bug. There has been updates to itext (iiif-server version was 5.5.13, we're now at 7.1.7), let's first test that. Then if it doesn't work, I've prepared a small code template that you can fill with the appropriate code so that we can report the bug, see https://github.com/buda-base/buda-iiif-server/commit/95bf7dfbfa7922b32d72594f33aff773e28012dd

can you make the two functions and copy the pdf results here? (I don't have webp-imageio on my system so the thing doesn't work)

**Comment by MarcAgate** [comment]
The tmp file issue has been fixed and the issue reported here [https://stackoverflow.com/questions/57113834/why-are-some-images-cropped-in-pdfs](https://stackoverflow.com/questions/57113834/why-are-some-images-cropped-in-pdfs)

**Comment by eroux** [comment]
thanks for investigating this!
