### ISSUE TITLE
error 500 on pdf

### ISSUE THREAD

**Issue by eroux** [buda-base/buda-iiif-server#42]
I tried to download the first volume of W22084, the first time it took a very long time, but the second time it gave me a link to

http://iiif.bdrc.io/download/file/pdf/bdr:V22084_I0886:1-624

which is a 500 error

**Comment by MarcAgate** [comment]
This is weird as I tried this 
http://iiif.bdrc.io/download/pdf/v:bdr:V22084_I0886::1-624 
that led me to this
http://iiif.bdrc.io/download/file/pdf/bdr:V22084_I0886:1-624 
which gave me the expected file.

**Comment by eroux** [comment]
ok, there are probably a few glitches in the api, but I've been able to get the pdf, let's ignore that for now, thanks!
