### ISSUE TITLE
issue with resized images

### ISSUE THREAD

**Issue by eroux** [buda-base/buda-iiif-server#44]
The following URL gives an erroneous output:

https://iiif.bdrc.io/bdr:V22334_I3867::38670133.tif/full/,2000/0/default.png

while this one is ok:

https://iiif.bdrc.io/bdr:V22334_I3867::38670133.tif/full/max/0/default.png

**Comment by MarcAgate** [comment]
The original image size is 5014 x 592. The resizing fails as soon as the requested height is bigger than 592.

**Comment by eroux** [comment]
thx, closing in favor of https://github.com/buda-base/public-digital-library/issues/93
