### ISSUE TITLE
Fair use

### ISSUE THREAD

**Issue by MarcAgate** [buda-base/buda-iiif-server#50]
iiif server pdfs of Fair_use works always return 41 pages regardless the use profile. In other words, an admin user has no way to access the entire work.

**Comment by eroux** [comment]
I made some changes with the fair use stuff in the newbiblio branch, so please use it instead of master for this

**Comment by MarcAgate** [comment]
I am talking about the biblio branch. The imageList comes from the IdentifierInfo class that doesn't  know about the AccessLevel of the user. [Here](https://github.com/buda-base/buda-iiif-server/blob/newbiblio/src/main/java/io/bdrc/iiif/resolver/IdentifierInfo.java#L63) and [Here](https://github.com/buda-base/buda-iiif-server/blob/newbiblio/src/main/java/io/bdrc/iiif/resolver/IdentifierInfo.java#L47 )

**Comment by eroux** [comment]
ok yes, thanks! note that it's quite important to keep having the complete list in the cache, etc. and then deriving another one for the fairuse case

**Comment by MarcAgate** [comment]
I believe the per image treatment of fair use case is ok. The problem only occurs with the pdf/zip builder that uses ensureImageListInfo() in IdentifierInfo.
Regarding the needs to always have the full list of images in the cache, I see that the current implementation of IdentifierInfo doesn't fulfill it since it produces a limited list for a ImageGroup having a FairUse Access.
I am going to address both issues then.
