### ISSUE TITLE
500 errors

### ISSUE THREAD

**Issue by eroux** [buda-base/buda-iiif-server#51]
I just got another 500 error, on https://iiif-dev.bdrc.io/bdr:I4CZ75259::I4CZ752590001.tif/info.json , see:

![Capture d’écran de 2020-03-24 10-48-23](https://user-images.githubusercontent.com/60868/77411758-3396f880-6dbd-11ea-9503-9c91f51c4169.png)

this should be very high priority

**Comment by MarcAgate** [comment]
Fixed as of commit 42e2dab
