### ISSUE TITLE
redirection problem

### ISSUE THREAD

**Issue by eroux** [buda-base/buda-iiif-server#55]
When accessing the URI of a iiif service, such as

https://iiif-dev.bdrc.io/bdr:I00KG06686::I00KG066860003.tif

there should be either a proper redirect to the `/info.json` version of the URI or the jsonld should be served directly. Currently we have a very weird response that confuses the browser

**Edit:** see [this part of the spec](https://iiif.io/api/image/2.1/#uri-syntax): 

> When the base URI is dereferenced, the interaction should result in the image information document. It is recommended that the response be a 303 status redirection to the image information document’s URI. Implementations may also exhibit other behavior for the base URI beyond the scope of this specification in response to HTTP request headers and methods.

**Comment by MarcAgate** [comment]
Fixed as of commit f38da0e

**Comment by eroux** [comment]
thanks!
