### ISSUE TITLE
error when stressing server for PDFs

### ISSUE THREAD

**Issue by eroux** [buda-base/buda-iiif-server#58]
see https://github.com/buda-base/public-digital-library/issues/214#issuecomment-673574380

**Comment by MarcAgate** [comment]
Well... there's not even the word "exception" in iiifserv file for at least the last 4 and 1/2 hour...

**Comment by eroux** [comment]
ah, that's a very bad sign... maybe something in `catalina.out`?

**Comment by eroux** [comment]
otherwise let's make the log level lower (info or something like that) and see if the requests are well received, that will be a first step
