### ISSUE TITLE
handle imageSourceType in archive generation 

### ISSUE THREAD

**Issue by eroux** [buda-base/buda-iiif-server#60]
currently it can only get images from s3

**Comment by eroux** [comment]
we need to make it run on local drive for the Chinese mirror. @MarcAgate do you think you might have time to take care of that?

**Comment by MarcAgate** [comment]
S3 is actually handled directly in ImageProviderService and references in both ArchiveBuilder and ArchiveImageProducer were actually unused. I just removed them in commits 3ae6bba and 983c47d

**Comment by eroux** [comment]
that works, thanks a lot!
