### ISSUE TITLE
not using disk cache for images when images are on disk already

### ISSUE THREAD

**Issue by eroux** [buda-base/buda-iiif-server#65]
we should have an option (that we would use on the Chinese server) that prevents the use of caching for images (but keeps it for PDF and ZIP), as the cache is on the same hard drive as the images themselves, so that doesn't have a lot of sense

@MarcAgate if at some point you have time for that don't hesitate!

**Comment by MarcAgate** [comment]
Done as of commit 95278ad

**Comment by eroux** [comment]
great, thanks!
