### ISSUE TITLE
(almost) synchronous PDF generation

### ISSUE THREAD

**Issue by eroux** [buda-base/buda-iiif-server#67]
This should be an option (that we'll turn on on the Chinese server):

The HTTP API would stay the same in this feature, but we would have:
- the API pretend that the PDF is generated and give the link
- when the PDF link is requested, all the images should be fetched one after the other, in a single thread (not one thread per image)

The reason is that the PDF generation still hangs when there are a lot of requests on the Chinese server

**Comment by MarcAgate** [comment]
Done as of 01c8276
I believe this will slightly impact archive generation performances. To what extent ? I cannot say. It has to be determined upon prod server characteristics and usage monitoring.
