### ISSUE TITLE
unable to generate PDF

### ISSUE THREAD

**Issue by eroux** [buda-base/buda-iiif-server#69]
When I try to generate a PDF for bdr:W3CN4826 it doesn't seem to work at all (the http query never returns)

**Comment by MarcAgate** [comment]
At least, I have the following message in the console (only for that url - the corresponding ZIP archive is built and served just fine):

`Access to fetch at 'https://iiif.bdrc.io/download/pdf/v:bdr:I3CN4828::1-' from origin 'https://library.bdrc.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`
