### ISSUE TITLE
error on image

### ISSUE THREAD

**Issue by eroux** [buda-base/buda-iiif-server#80]
https://iiif.bdrc.io/bdr:I1NLM2232_001::I1NLM2232_0010001.jpg/full/,600/0/default.jpg

**Comment by eroux** [comment]
@TBRC-Travis @jimk-bdrc I'm describing the issue just FYI. No action to take on your part, except perhaps https://github.com/buda-base/asset-manager/issues/125 in the future. What happens is:
- the URL of the image requests the IIIF server to produce a 600px wide version of the image instead of the original, this means that the IIIF server must decode the JPG, resize it to fit the requested size, and reencode it
- because Java image processing is... bad... we can't extract the ICC profile of a decoded picture without a very big hit on performance (in Python this would be a non-issue)
- so we resort to a hack where we read at most the first `x` bytes of the original image, try to find the ICC profile in there, then go back to the beginning of the bytes (the [reset](https://docs.oracle.com/javase/7/docs/api/java/io/InputStream.html#reset()) function) and then decode the image
- this works when `x` is large enough to go to the end of the header where the ICC profile is
- in that case (because of the thumbnail), `x` wasn't large enough
- I've raised `x` from 40k to 60k, which solves this issue

**Comment by jimk-bdrc** [comment]
There's an implicit request here to extract and store this information from inside audit tool. It's intriguing, and should be part of a general ingest step. I'll flesh this out in asset-manager#125

**Comment by eroux** [comment]
Here's another failure: https://iiif.bdrc.io/bdr:I8LS26144::I8LS261440003.jpg/full/,500/0/default.jpg
