### ISSUE TITLE
Broken thumbnails in W24829

### ISSUE THREAD

**Issue by TBRC-Travis** [buda-base/buda-iiif-server#92]
@eroux all the thumbnails for [W24829](https://library.bdrc.io/show/bdr:W24829) are broken.  the pages themselves load fine.

<img width="866" alt="Screen Shot 2022-03-16 at 11 20 37 AM" src="https://user-images.githubusercontent.com/19354126/158625169-f36be7c7-dc80-4521-86f2-19dbd5949717.png">

**Comment by eroux** [comment]
this took a lot of time to be fixed, sorry for that! I now works, see https://github.com/buda-base/archive-ops/issues/882
