### ISSUE TITLE
don't offer first / last 20 pages in China for fairUse scans

### ISSUE THREAD

**Issue by eroux** [buda-base/buda-iiif-server#94]
(all in the title)

**Comment by eroux** [comment]
I'm looking into that issue but there's a very strong downside to restricting all the images of copyrighted works for users in China: they won't see any thumbnail in the search... @JannTibetan what do you think of allowing users to see the first 3 images only in China? Most thumbnails are in this range

**Comment by JannTibetan** [comment]
Google Books shows book covers for many works, whether or not it offers any amount of access to the books' contents. So there is this precedent. However I wonder if Google is getting the cover images of copyrighted works directly from the publishers and are therefore using the images with permission (it would seem so; the thumbnails don't look like scans). 
Even if China has virtually no fair use exceptions, it would seem that a thumbnail of a book cover, and nothing else, is acceptable. Let's ask a few more people about this.
<img width="682" alt="Screen Shot 2022-04-21 at 8 35 00 AM" src="https://user-images.githubusercontent.com/44705185/164459065-a44420d5-ef88-49f2-8ce4-d3c33a6c0096.png">

**Comment by eroux** [comment]
hmm, ok! we can perhaps ask Google Books? amazon (and the Chinese equivalents) have thumbnails for second hand books I think...

Well, I just remembered this one: https://books.google.fr/books?id=0s5Yp5Ls7IQC&hl=fr&source=gbs_book_other_versions it's been out of print for 80 years, it still under copyright from Google Books' perspective, but it has a thumbnail that's a scan

**Comment by JannTibetan** [comment]
Yes, many of their thumbnails are scans, including in the screen grab above.
I think it's probably OK if it's allowed on commercial sites such as bon resellers.

**Comment by eroux** [comment]
I've just deployed a version of the iiif server that only allows users to access the image that we are using as thumbnail. @JannTibetan do you think we should also restrict the maximum resolution of the image or is it ok if users can access the full version?

**Comment by JannTibetan** [comment]
Is the thought that offering only a low-res image of the cover further protects us from claims of copyright infringement? 

Perhaps instead (or, in addition to doing this) we also include a claim in Chinese that says something like, "Cover image made available for references purposes only and not for the benefit of BDRC."

Good explanation of the situation in the American context https://psu.libanswers.com/faq/336502
